platform :ios,'8.0' 
target'MerShop'do  
pod'AFNetworking','~> 2.6'
pod 'SDWebImage'
pod 'JSONModel'
pod 'MJRefresh', '~> 1.1.0'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'MJExtension'
pod 'Bugtags'
pod 'JWBluetoothPrinte'
pod 'UMCCommon'
pod 'UMCPush'
pod 'UMCSecurityPlugins'
pod 'BRPickerView'
pod 'JhtMarquee'
end
